version: '3'
services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '8090:80'
    depends_on:
      - api
    restart: always

  api:
    build: ./TodoApi/
    environment:
      - Redis_HOSTNAME=redis
    ports:
      - '5000'
    restart: always
    depends_on:
      - redis
    
  redis:
     image: "redis:alpine"
     environment:
      - REDIS_REPLICATION_MODE=master
     ports:
      - '6379:6379'
      
  redis_commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander
    restart: always
    environment:
    - REDIS_HOST=redis
    ports:
    - "8085:8081"